<a href="https://colab.research.google.com/github/Jainam66/Data-Science-1-to-70-days-challenge/blob/main/Day2_Pandas1_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here's a list of the primary tasks you can accomplish with the pandas library


1.Data Loading
2.Data Exploration and Inspection
3.Data Cleaning
4.Data Manipulation
5.Data Analysis
6,Data Visualization
7.Time Series Analysis
8.Handling Categorical Data
9.Data Transformation
10.Data Aggregation and Summarization
11.Data Exporting
12.Advanced Indexing and Selection
13.Working with Missing Data
14.Statistical Modeling and Analysis

In [2]:
import pandas as pd

In [11]:
#Functions in Pandas
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '_typing',
 '_version',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

Data Loading

In [5]:
df=pd.read_csv("/content/Salaries.csv")

In [32]:
df

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]


Data Exploration and Inspection

In [33]:
#parameters
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [34]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [35]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [10]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [37]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [38]:
df['salary']

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [39]:
df.salary.quantile(0.25)

88612.5

In [40]:
df.salary.quantile(0.75)

126774.75

In [41]:
df.std()

<ipython-input-41-ce97bb7eaef8>:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.std()

phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64

In [42]:
df_5000=df.head(50)

In [43]:
df_5000.mean()

<ipython-input-43-aaaab47b66c8>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_5000.mean()

phd            21.52
service        17.60
salary     113789.14
dtype: float64

2 Data structures in pandas #series (one dimensional labeled array) #DataFrame (two dimensional labeled array)

In [44]:
#series
result1=df.salary
type(result1)

pandas.core.series.Series

In [45]:
#DataFrame
result2=df[["salary","rank"]]

In [46]:
result2
type(result2)

pandas.core.frame.DataFrame

In [48]:
#category and #unique value and its value count
df['rank'].value_counts()

Prof         46
AsstProf     19
AssocProf    13
Name: rank, dtype: int64

Calculate the Basic Statistics of the Population Column
Calculate the Average of Population

In [49]:
df.salary.describe()

count        78.000000
mean     108023.782051
std       28293.661022
min       57800.000000
25%       88612.500000
50%      104671.000000
75%      126774.750000
max      186960.000000
Name: salary, dtype: float64

In [50]:
df.salary.count()

78

In [51]:
df.salary.mean()

108023.78205128205

Group By this and find mean of each category
Group by and find the mean of all the numeric column

In [52]:
df.groupby(['rank']).mean()

<ipython-input-52-59c8c915524f>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['rank']).mean()

                 phd    service         salary
rank
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [53]:
grouped=df.groupby('rank')

In [54]:
grouped

In [55]:
for g in grouped:
  print(g)

('AssocProf',          rank discipline  phd  service     sex  salary
6   AssocProf          A   20       17    Male   81285
30  AssocProf          B    9        7    Male  107008
34  AssocProf          B   12        8    Male  119800
41  AssocProf          A   13        8  Female   74830
47  AssocProf          B   11       11  Female  103613
54  AssocProf          A   25       22  Female   62884
56  AssocProf          A   10        8  Female   77500
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
64  AssocProf          A   26       24  Female   73300
71  AssocProf          B   12        9  Female   71065
74  AssocProf          B   19        6  Female  104542)
('AsstProf',         rank discipline  phd  service     sex  salary
12  AsstProf          B    1        0    Male   88000
16  AsstProf          B    8        3    Male   75044
17  AsstProf          B    4        0    Male   92000
20  AsstProf          B    4        4    Male   92000
22  AsstProf          A    4        2    Male   73000
23  AsstProf          A    2        0    Male   85000
28  AsstProf          B    7        2    Male   91300
38  AsstProf          B    4        3    Male   91000
42  AsstProf          B    4        2  Female   80225
43  AsstProf          B    5        0  Female   77000
46  AsstProf          B   11        3  Female   74692
50  AsstProf          B   10        5  Female   97032
53  AsstProf          A    5        3  Female   73500
55  AsstProf          A    2        0  Female   72500
57  AsstProf          A    3        1  Female   72500
60  AsstProf          B    3        3  Female   92000
66  AsstProf          A    7        6  Female   63100
68  AsstProf          A    4        2  Female   77500
70  AsstProf          A    8        3  Female   78500)
('Prof',     rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   12        6    Male   93000
2   Prof          A   23       20    Male  110515
3   Prof          A   40       31    Male  131205
4   Prof          B   20       18    Male  104800
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
8   Prof          A   29       19    Male   94350
9   Prof          A   51       51    Male   57800
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
18  Prof          A   19        7    Male  107300
19  Prof          A   29       27    Male  150500
21  Prof          A   33       30    Male  103106
24  Prof          A   30       23    Male   91100
25  Prof          B   35       31    Male   99418
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
32  Prof          A   27       19    Male  103275
33  Prof          B   18       18    Male  120000
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
37  Prof          A   20        8    Male  102000
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
48  Prof          B   17       17  Female  111512
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
52  Prof          A   12        0  Female  105000
58  Prof          B   36       26  Female  144651
63  Prof          A   29       27  Female   91000
65  Prof          A   36       19  Female  117555
67  Prof          A   17       11  Female   90450
69  Prof          A   28        7  Female  116450
72  Prof          B   24       15  Female  161101
73  Prof          B   18       10  Female  105450
75  Prof          B   17       17  Female  124312
76  Prof          A   28       14  Female  109954
77  Prof          A   23       15  Female  109646)

In [57]:
df[df.salary>120000]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

Shape of dataset

In [58]:
df.shape

(78, 6)

In [59]:
df.shape[0]

78

In [60]:
df[df.salary>120000].count()

rank          25
discipline    25
phd           25
service       25
sex           25
salary        25
dtype: int64

create a dataframe having all males whose salary is >150000

In [6]:
df

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [10]:
  NEWDF=df[(df['sex']=='Male')&(df['salary']>150000)]
  NEWDF

    rank discipline  phd  service   sex  salary
0   Prof          B   56       49  Male  186960
13  Prof          B   35       33  Male  162200
14  Prof          B   25       19  Male  153750
15  Prof          B   17        3  Male  150480
19  Prof          A   29       27  Male  150500
27  Prof          A   45       43  Male  155865
31  Prof          B   22       21  Male  155750